services:
  # Contenedor para la base de datos principal
  db_main:
    image: mysql:8.0
    container_name: db_main
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
    ports:
      - "3310:3306"  # Mapea el puerto 3306 del contenedor al puerto 3306 en tu máquina
    networks:
      - app-network

  # Contenedor para la base de datos de usuarios
  db_users:
    image: mysql:8.0
    container_name: db_users
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
      MYSQL_USER: users_user
      MYSQL_PASSWORD: users_password
    volumes:
      - mysql_data_users:/var/lib/mysql
    ports:
      - "3311:3306"
    networks:
      - app-network

  web:
    build: .
    command: bash -c "/start.sh"
    volumes:
      - .:/app
      - ./start.sh:/start.sh:ro
    ports:
      - "8000:8000"
    depends_on:
      - db_main
      - db_users
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_data_users:

networks:
  app-network:
    driver: bridge
