# Generated by Django 3.2.25 on 2025-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planimetry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('name_alt', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Aprobado', 'Aprobado'), ('En trámite', 'En trámite'), ('Rechazado', 'Rechazado')], max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('speciality', models.CharField(max_length=50)),
                ('urn', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('dwg', 'DWG'), ('revit', 'Revit'), ('otros', 'Otros')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
