# Generated by Django 3.2.25 on 2025-10-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_project', '0001_initial'),
        ('planimetries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomenclature', models.CharField(max_length=50)),
                ('buildings_amount', models.PositiveIntegerField()),
                ('planimetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='planimetries.planimetry')),
                ('proyect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='templates_project.projecttemplatetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
