# Generated by Django 3.2.25 on 2025-10-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        ('planimetries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('usage', models.CharField(max_length=20)),
                ('ind_desc', models.CharField(max_length=20)),
                ('indicator', models.CharField(max_length=20)),
                ('min_usable_area', models.CharField(max_length=20)),
                ('coefficient_security', models.CharField(max_length=20)),
                ('data_source', models.CharField(max_length=20)),
                ('generalities', models.CharField(max_length=20)),
                ('planimetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='planimetries.planimetry')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='zones.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
